package com.codefab.token;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET,
    SEMICOLON, COMMA,

    PLUS, MINUS, STAR, SLASH,
    SEMICOLON,
    PLUS, MINUS, STAR, SLASH, PERCENT,
    EQUAL, GREATER, LESS, BANG,
    EQUAL_EQUAL, BANG_EQUAL, GREATER_EQUAL, LESS_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    VAR, IF, ELSE, FOR,
    TRUE, FALSE,
    AND, OR,
    PRINT,
    FUNC, RETURN,

    EOF
}
